### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by Adelaam** [LooseLab/bulkvis#22]
Hello,

Can you help me with the installation?

cd bulkvis
python utils/set_confi.py -b <<bulkfile>> -i /path/to/bulkfile/directory -e /path/to/readfile/directory -m /path/to/mapfile/directory -c config.ini

On this step:
-i is the path to my folder which I clone?
-e: readfile? 
-m: mapfile?

Thank you!

**Comment by alexomics** [comment]
The options are: 

- `-i` is the full path to your folder containing bulk fast5 files that you want to visualise
- `-e` is the full path to a folder where read fast5 files generated by bulkvis will be saved
- `-m` is the full path to the folder where map files, generated by `gen_bmf.py`, are stored

On windows this will take the form 
```
"C:\path\to\bulkfile\folder\"
```
On linux or Mac OS X
```
/path/to/bulkfile/directory/
```

These should start from the top level of the drive.

**Comment by alexomics** [comment]
Alternatively, you can take a look at the the [config page](https://github.com/LooseLab/bulkvis/blob/master/config.md) and copy/edit the example there.

**Comment by Adelaam** [comment]
Hello,

Thank you for your answer.

~/bulkvis$ python utils/set_confi.py -b <<bulkfile>> -i'/media/markwilks/Elements/Data/workspace/pass/barcode01' -e '/home/markwilks/Bulkvisresults' -m '/home/markwilks/bulkvis/utils/gen_bmf.py' 
>
I have done what you said and now? It is thinking is there something wrong?

**Comment by Adelaam** [comment]
-b '/home/markwilks/bulkvis'

**Comment by alexomics** [comment]
This is the help text from `set_config.py`

```bash 
Generate a configuration file required for bulkvis to run

General options:
  -h, --help          Show this help and exit

Input sources:
  -b , --bulkfile     A bulk-fast5 file to get labels from
  -i , --input-dir    The path to the folder containing bulk-files for
                      visualisation
  -e , --export-dir   The path to the folder where read-files will be written
                      by bulkvis
  -m , --map-dir      The path to the folder where map files, created by
                      gen_bmf.py, are stored

Output:
  -c , --config       Path to the config.ini file in your bulkvis installation
```

All the input sources are required parameters. 

For me the command would look like:
```bash
python utils/set_config.py -b /home/alex/bulkfiles/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5 -i /home/alex/bulkfiles/ -e /home/alex/bulkvis_export/ -m /home/alex/bulkvis_map/
```

**Comment by Adelaam** [comment]
Thank you!

**Comment by asyofasyo** [comment]
Hello!

 Where can I find .fast5 file to get the labels from? I don' see it in 'bulkvis' directory and any other documentation 

 Thanks, Anastasiia

**Comment by alexomics** [comment]
Hi Anastasiia, 

The .fast5 files are provided by you, from your sequencing experiments. If you are having trouble installing/using bulkvis could you please open a new issue.

Alex
