### ISSUE TITLE
Bulk FAST5 used in BulkVis Bioinformatics publication

### ISSUE THREAD

**Issue by Damien-Black** [LooseLab/bulkvis#30]
This is a question,

I'm trying to launch the browser and view the signal data as you do in Figure 2 of [BulkVis Paper](https://academic.oup.com/bioinformatics/article/35/13/2193/5193712). Here's what I do:

1. Download the supplementary data you provide [HERE](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/35/13/10.1093_bioinformatics_bty841/2/bty841_supplementary_data.zip?Expires=1581630456&Signature=IWNE-uFA3woROMWBlzy8E0xseGCS28ns0XBxoz5VPGkCCni9piYkT2XmxBscRJ6NwLzuAACzJFCvwIxDpKtgSupaHOSqVshBNPl14fusr3bCAENMxKApfFDita6sb3LP7J7hvmqETBEWL6YoHgGeAdtp1tK4vrOj5AWbeL34xo7DuF85-JXy82hM52UxFB0TKRxIE6TSTgPRCVplF2JXbZvNEkDBdSrie4aYM2pwYHZRDENXF9psaTSK33~S4-mW9VeUnkEoz5s59rdgCgmWHLdQRUImzDWN4Flp-J3FBWLd4e1iFNQVzpQ3HtX-Lh7yb5eZXM1VcRsQg5mO42zViw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA)
2. Install BulkVis as specified in the [installation](https://github.com/LooseLab/bulkvis/blob/master/docs/installation.rst).
3. Attempt to configure for `Collection001` data set.
  * I run into an issue when attempting to run set_config.py, I don't know where the bulkfile from the original MinION run is.

Is it possible to get access to the bulkfile so I'm able to properly configure BulkVis?

**Comment by alexomics** [comment]
Hi Damien, 

The bulk FAST5 file used in the paper can be downloaded from http://s3.amazonaws.com/nanopore-human-wgs/bulkfile/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5

This is a 21GB file, so it may take a while to download.

Alex

**Comment by Damien-Black** [comment]
Thanks @alexomics!

**Comment by liu-pinnng** [comment]
Hi Alexomics,

I checked the bulk raw output items, however, still could not achieve analyzable bulk FAST5?
Could you tell me how to achieve analyzable bulk FAST5?
Thank you in advance.
