### ISSUE TITLE
issue with whale_merge.py (file format ?)

### ISSUE THREAD

**Issue by btheulot** [LooseLab/bulkvis#38]
I'm now trying whale_merge as whale_watch is working.
Our fastq id string as this format : 

> @ch134_read207_45c3878c-f8ae-4aee-8e48-93e8f8e1e332_pass_FAL84658

It is different from the format for which the script is supposed to work.

I have modified a part of the  whale_watch.py script in order to make it work with our fastq format

```
                while line:
                    if len(line.split('_')) > 1: #means we have a fastq ID line
                        if cnt%400 == 0:
                            print(myreadtracker.result())
                        read_id = line.split('_')[2]
```
However it doesn't produce the new fastq at the end, and I don't get any error messages. I'm not really familiar with python, am I missing something to adapt the script ?

**Comment by alexomics** [comment]
So at the moment, our code expects the read header to be in the standard MinKNOW format:

```
@<READ_ID> runid=<RUN_ID> read=<READ_NUMBER> ch=<CHANNEL> start_time=<TIME>
```

It looks like your change selects the read id, but we cannot guarantee that this change will work. If you're able to change the read headers to be in the format:

```
@<READ_ID> ...
```
then this should work, but this case was not considered when this was originally written.

**Comment by btheulot** [comment]
Sorry for my late reply.
Indeed we now realized that our sequencing plateform has a different type of format, making it very 
restrictive for using other soft... We will ask them to use the standard format in the futur.
