### ISSUE TITLE
create bulk FAST5 file

### ISSUE THREAD

**Issue by alexomics** [LooseLab/bulkvis#43]
Hi Alexomics,

I checked the bulk raw output items, however, still could not achieve analyzable bulk FAST5?
Could you tell me how to achieve analyzable bulk FAST5?
Thank you in advance.

_Originally posted by @liu-pinnng in https://github.com/LooseLab/bulkvis/issues/30#issuecomment-742241001_

**Comment by alexomics** [comment]
@liu-pinnng When you start a sequencing run, under the `output` section there is an `Advanced User Options` section. In there you can turn on the "bulk file" option which will save a bulk FAST5 file that is compatible with bulkvis for that sequencing run.

**Comment by liu-pinnng** [comment]
Hi Alex,

Thank you for your information.
I turned the "bulk file" option on.
Do i still need to check the raw output items?

Ping

Alex <notifications@github.com> 於 2020年12月10日 週四 下午8:10寫道：
