### ISSUE TITLE
bulk fast5 file

### ISSUE THREAD

**Issue by mmpust** [LooseLab/bulkvis#49]
Hello, 

thank you for developing this game-changing tool!  

One question regarding the .fast5 files. If I did not switch on the "bulk fast5 option" before starting the sequencing run, can I still generate the bulk file from individual .fast5 files by concatenating the individual files?

Thanks!

**Comment by alexomics** [comment]
Hi, 

Unfortunately you can't recreate the bulk FAST5 file from the individual read files. It can only be turned on at the start of the sequencing run at the moment. 

Best, 
Alex
