### ISSUE TITLE
How can I check I have the correct bulk-fast5 file?

### ISSUE THREAD

**Issue by francoiskroll** [LooseLab/bulkvis#51]
I did not do that sequencing run first-hand. Is there anyway I can check I have the right bulk-fast5 files to use with bulkvis?

For example, one of my file:

filename = AGQ569_pass_barcode12_3dd4cb83_0.fast5
size = 62.3 Mb

Does that sound plausible to you?

Given the size I'm pretty sure it's not single-read (it was also after Guppy changed from single-read fast5 files, if I remember correctly), but I am a bit confused if "bulk" means something more specific here.

For example, I read the example bulk5 you provide is 21 Gb. Does that mean bulk-fast5 = one fast5 for the whole run? In which case I might not have the right data format.

**Comment by alexomics** [comment]
From the filename I think that you have a multi-read FAST5 file. Unfortunately, these are not compatible with bulkvis. If you attempt to run bulkvis from the [v2.0](https://github.com/LooseLab/bulkvis/tree/2.0) branch and run `bulkvis serve <FAST5-FOLDER>` any files that are bulk FAST5 files will show up in the drop down.

There are some instructions for how to collect a bulk FAST5 file on the [ONT community](https://community.nanoporetech.com/protocols/experiment-companion-minknow/v/mke_1013_v1_revbm_11apr2016/starting-a-sequencing-run-on-minion), see step 10.

**Comment by francoiskroll** [comment]
Wow quick! Appreciate it.

Okay. So single-read ≠ multi-read ≠ bulk, I see.

And from what I can read, you can swap between single-read and multi-read using ONT's `ont_fast5_api`, but bulk is its own thing.

Thank you
