### ISSUE TITLE
Location of NC_sequencing.py

### ISSUE THREAD

**Issue by esh97** [LooseLab/bulkvis#57]
I recently updated my version of Minknow and now cannot locate the necessary py script to turn on the saving of bulk files. Is there a way to locate this script and/or which folders should I be looking in?

Thanks for your help

**Comment by mattloose** [comment]
Off the top of my head I don't know where this is set programatically, but it can be done through the MinKNOW GUI under the advanced options when setting the output function:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/8202484/234491530-37221052-3373-436e-80cd-fdacae01f58c.png">

Note that the required boxes to tick are the "raw" and "read table" - events are not required.

I think the file you are looking for has been renamed to sequencing.py?
