### ISSUE TITLE
ERROR: Failed building wheel for numpy

### ISSUE THREAD

**Issue by Grant-Fox** [LooseLab/bulkvis#59]
Hello Bulkvis team,

I am inquiring for help in relation to an error that fails to build wheel for numpy.

Command lines:
`python3 -m venv bulkvis`
`source bulkvis/bin/activate`
`pip3 install git+https://github.com/LooseLab/bulkvis.git@2.0`

Error: 
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Would be great if assistance could be provided. Thank you!

**Comment by enderdmeise** [comment]
same error here

**Comment by mattloose** [comment]
Hi - we'll look into this asap.

**Comment by mattloose** [comment]
Could you confirm what operating system you are using please?

**Comment by enderdmeise** [comment]
i'm on windows 10 running python 3.10

trying this now: https://github.com/LooseLab/bulkvis/issues/40#issuecomment-650112303

edit: also fails (pip 23.1.2, Python 3.11.4, Win10)

**Comment by alexomics** [comment]
I've pushed soem looser install requirements to the `issue59` branch. Can you attempt either a *conda* or *pip* install:

### conda
```yaml
name: bulkvis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - git+https://github.com/LooseLab/bulkvis.git@issue59
```

Either copy the YAML above into a file or:

```console
curl -O https://raw.githubusercontent.com/LooseLab/bulkvis/issue59/env.yml
conda env create -f env.yml
```

### pip

```console
python3 -m venv venv 
source venv/bin/activate 
pip install -U pip setuptools wheel
pip install git+https://github.com/LooseLab/bulkvis.git@issue59
```

---

After installing with one of the above you can then start bulkvis using:
```console
conda activate bulkvis
bulkvis serve <BULK_FILE_DIRECTORY> --show
```

Please let us know if you hit any issues with either of these. And please include any error messages/details so that we can troubleshoot it.

**Comment by enderdmeise** [comment]
installation now completes sucvcessfully using the following procedure:

installed Python 3.11.4 from python website (Win10-x64)
within a venv (virtualenv) run the two commands as suggested:
>pip install -U pip setuptools wheel
>pip install git+https://github.com/LooseLab/bulkvis.git@issue59

but, running the bulkvis serve command thows:
ERROR: Path for Bokeh server application does not exist: [...]\venv\Lib\site-packages\bulkvis\bulkvis_server

**Comment by alexomics** [comment]
What was the command that you used to start bulkvis?

**Comment by enderdmeise** [comment]
bulkvis serve <BULK_FILE_DIRECTORY> --show

after quickly cloning the repo and copying the folder "\bulkvis\bulkvis_server" from the source code to "\venv\Lib\site-packages\bulkvis\bulkvis_server" the bokeh server starts up successfully

edit: although i'm not seeing the .fast5 bulkfile located in the specified dir in the dropdown, but this is probably just a user error on my side (first time bulkvis user^^)

**Comment by alexomics** [comment]
Can you confirm that the folder `bulkvis\bulkvis_server` is missing from the `site-packages` folder on a fresh installation?

If you're not seeing any bulk FAST5 files in the dropdown there's a couple of possibilities:
1. It's a newer bulk FAST5 that requires [vbz plugins](https://github.com/nanoporetech/vbz_compression)
2. It's not a bulk FAST5 that we can use; for testing we recommend using [PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5](http://s3.amazonaws.com/nanopore-human-wgs/bulkfile/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5) from the publication, but it is ~21Gb

--- 

For the avoidance of doubt, when you run the `bulkvis serve <BULK_FILE_DIRECTORY> --show` command, you are replacing the `<BULK_FILE_DIRECTORY>` with the path to your bulk FAST5 folder? E.G: 
```console
bulkvis serve ~/data/bulkfiles --show
```

**Comment by enderdmeise** [comment]
I can verify that after deleting the venv and installing completely fresh that the bulkvis_Server folder is missing from the installation. these are all the contents of the bulkvis-lib:
`\venv\Lib\site-packages\bulkvis>dir /b`
bulkvis.py
cite.py
core.py
fuse.py
mappings.py
merge.py
serve.py
_version.py
__init__.py
__pycache__

my install process:

`py --list`
 -V:3.11 *        Python 3.11 (64-bit)
 -V:3.6            Python 3.6 (64-bit)

`py -3.6 -m virtualenv venv` (also verified with fresh install using a venv with python 3.11)
`venv\Scripts\activate`
`pip install -U pip setuptools wheel`
`pip install git+https://github.com/LooseLab/bulkvis.git@issue59`

`pip freeze`
bokeh==2.3.3
bulkvis @ git+https://github.com/LooseLab/bulkvis.git@2649b6cedd33ba81d583b698aeadb2f0efa69591
cached-property==1.5.2
colorama==0.4.5
h5py==3.1.0
importlib-resources==5.4.0
Jinja2==3.0.3
MarkupSafe==2.0.1
numpy==1.19.5
packaging==21.3
pandas==1.1.5
Pillow==8.4.0
pyparsing==3.1.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
readpaf==0.0.10
six==1.16.0
tornado==6.1
tqdm==4.64.1
typing_extensions==4.1.1
zipp==3.6.0

---

yes, this is the exact command I use to run: `bulkvis serve Z:\NGS_run1_230621 --show`
it is a recently created bulkfile, thus I followed the instruction to install vbz plugins, but I'll definitely troubleshoot using the file you recommended for testing.

btw, thank a bunch for your help and being super responsive!

**Comment by alexomics** [comment]
Okay, I've pushed a small change. Can you try a fresh install again? I'm sorry I don't have access to a Windows PC to check these on!

**Comment by enderdmeise** [comment]
yes, I can confirm that bulkvis_server now correctly installs on commit b954d478d2c3db94c5c20f2e27ceeee87cbde2f3

**Comment by alexomics** [comment]
Perfect, I will merge that in now. 

@Grant-Fox I'm going to mark this as resolved for now, if you can attempt re-installing from the `2.0` branch when you get a chance and if it doesn't work please re-open this issue.

**Comment by Grant-Fox** [comment]
> Can you confirm that the folder `bulkvis\bulkvis_server` is missing from the `site-packages` folder on a fresh installation?
> 
> If you're not seeing any bulk FAST5 files in the dropdown there's a couple of possibilities:
> 
>     1. It's a newer bulk FAST5 that requires [vbz plugins](https://github.com/nanoporetech/vbz_compression)
> 
>     2. It's not a bulk FAST5 that we can use; for testing we recommend using [PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5](http://s3.amazonaws.com/nanopore-human-wgs/bulkfile/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5) from the publication, but it is ~21Gb
> 
> 
> For the avoidance of doubt, when you run the `bulkvis serve <BULK_FILE_DIRECTORY> --show` command, you are replacing the `<BULK_FILE_DIRECTORY>` with the path to your bulk FAST5 folder? E.G:
> 
> ```
> bulkvis serve ~/data/bulkfiles --show
> ```

Hello Alex,

Thank you for your help. I was able to resolve the installation problem but I did run into the issue the directory of the fast5 files not being available after loading into the program. What is a bulk fast5 file verse the directory of fast5 files? I think I am missing this piece of information to understand this program.

**Comment by alexomics** [comment]
@Grant-Fox a bulk FAST5 file is a "debug" output from MinKNOW. Typically they are very large files as they record the raw stream of data from the sequencer (i.e. raw data is not segmented into reads) as well as live classifications that MinKNOW made during sequencing. A normal directory of FAST5 files typically contain the segmented reads.

Bulk FAST5 files are not typically written, but can be created using "Advanced options" on screen 5 when starting a run. 

You can download the [example bulk FAST5 file](http://s3.amazonaws.com/nanopore-human-wgs/bulkfile/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5) (~21Gb) and place that in the bulk-file directory to see if `bulkvis` detects it.
